import Head from 'next/head'
import Image from 'next/image'
import Tag from '../components/tag/tag'
import Welcome from '../components/welcome/welcome'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome />
      <Tag />
    </div>
  )
}
