import Head from 'next/head'
import Image from 'next/image'
import style from "../styles/Home.module.css"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.cover}>
        <div className={style.headings}>Welcome to LowPoly Documentation</div>
        <p>

        </p>

      </div>
    </div>
  )
}
